name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: githubactionsiti2025.azurecr.io
  IMAGE_NAME: somaya/ga-application

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f namespace.yaml
          kubectl --kubeconfig=kubeconfig apply -f mongo.yaml
          sed "s|somaya/ga-application:latest|$REGISTRY/$IMAGE_NAME:${{ github.sha }}|g" app.yaml | \
            kubectl --kubeconfig=kubeconfig apply -f -
