name: docker task

on:
  workflow_dispatch:

env:
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ vars.reg }}/${{ vars.username }}/${{ env.IMAGE_NAME }}:latest .

      - name: Docker Login
        run: echo "${{ secrets.PASSWORD }}" | docker login ${{ vars.reg }} --username "${{ vars.username }}" --password-stdin

      - name: Docker Publish
        run: docker push ${{ vars.reg }}/${{ vars.username }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: echo "${{ secrets.PASSWORD }}" | docker login ${{ vars.reg }} --username "${{ vars.username }}" --password-stdin

      - name: Docker Run
        run: docker run -d -p 8080:80 ${{ vars.reg }}/${{ vars.username }}/${{ env.IMAGE_NAME }}:latest
