name: workflow 1
on: 
  push:

jobs:
  somaya:
    needs: readme
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: |
          echo "Hello world"
          sudo apt update -y
          sudo apt install cowsay -y
          cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
          cat dragon.txt

  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Show README
        run: cat readme.md
